SET SERVEROUTPUT ON;
DECLARE
    V_DESCRIPCION VARCHAR2(50);
BEGIN
    SELECT DESCRIPCION INTO V_DESCRIPCION FROM PAISES;
    DBMS_OUTPUT.PUT_LINE('La lectura de la tabla PAISES fue exitosa' || V_DESCRIPCION);
END;

DECLARE
    V_DESCRIPCION VARCHAR2(50);
BEGIN
    SELECT DESCRIPCION INTO V_DESCRIPCION FROM PAISES WHERE CODIGO_PAIS = 'pa1';
    DBMS_OUTPUT.PUT_LINE('La lectura de la tabla PAISES fue exitosa ' || V_DESCRIPCION);
END;

DECLARE
    CURSOR C_PAISES IS
        SELECT *
        FROM PAISES;
    V_CODIGO_PAIS PAISES.CODIGO_PAIS%TYPE;
    V_DESCRIPCION PAISES.DESCRIPCION%TYPE;
    V_CONTINENTE  PAISES.CONTINENTE%TYPE;
BEGIN
    OPEN C_PAISES;
    LOOP
        EXIT WHEN C_PAISES%NOTFOUND;
        FETCH C_PAISES INTO V_CODIGO_PAIS, V_DESCRIPCION, V_CONTINENTE;
        DBMS_OUTPUT.PUT_LINE('Codigo Pais: ' || V_CODIGO_PAIS || ' Descripcion: ' || V_DESCRIPCION || ' Continente: ' ||
                             V_CONTINENTE);
    END LOOP;
    CLOSE C_PAISES;
END;

DECLARE
    CURSOR C_PAISES IS
        SELECT *
        FROM PAISES;
    REGISTRO C_PAISES%ROWTYPE;
BEGIN
    OPEN C_PAISES;
    LOOP
        EXIT WHEN C_PAISES%NOTFOUND;
        FETCH C_PAISES INTO REGISTRO;
        DBMS_OUTPUT.PUT_LINE('Codigo Pais: ' || REGISTRO.CODIGO_PAIS || ' Descripcion: ' || REGISTRO.DESCRIPCION ||
                             ' ' ||
                             'Continente: ' ||
                             REGISTRO.CONTINENTE);
    END LOOP;
    CLOSE C_PAISES;
END;

DECLARE
    CURSOR C_PAISES IS
        SELECT *
        FROM PAISES FOR
            UPDATE OF CONTINENTE;
    V_CODIGO_PAIS PAISES.CODIGO_PAIS%TYPE;
    V_DESCRIPCION PAISES.DESCRIPCION%TYPE;
    V_CONTINENTE  PAISES.CONTINENTE%TYPE;
BEGIN
    OPEN C_PAISES;
    FETCH C_PAISES INTO V_CODIGO_PAIS, V_DESCRIPCION, V_CONTINENTE;
    WHILE C_PAISES%FOUND
        LOOP
            UPDATE PAISES SET CONTINENTE = 'Continente ' || V_CONTINENTE WHERE CURRENT OF C_PAISES;
            FETCH C_PAISES INTO V_CODIGO_PAIS, V_DESCRIPCION, V_CONTINENTE;
        END LOOP;
    CLOSE C_PAISES;
    COMMIT;
END;

SELECT *
FROM PAISES;

CREATE OR REPLACE PROCEDURE SP_PRODUCTOS(XPRECIO IN NUMBER)
AS
BEGIN
    DECLARE
        CURSOR C_PRODUCTOS IS
            SELECT ID_PRODUCTO, DESCRIPCION
            FROM PRODUCTOS
            WHERE PRECIO > XPRECIO;
        v_CODIGO_PRODUCTO PRODUCTOS.ID_PRODUCTO%TYPE;
        v_DESCRIPCION     PRODUCTOS.DESCRIPCION%TYPE;
    BEGIN
        OPEN C_PRODUCTOS;
        LOOP
            FETCH C_PRODUCTOS INTO v_CODIGO_PRODUCTO, v_DESCRIPCION;
            EXIT WHEN C_PRODUCTOS%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE('Codigo Producto: ' || v_CODIGO_PRODUCTO || ' Descripcion: ' || v_DESCRIPCION);
        END LOOP;
        CLOSE C_PRODUCTOS;
    END;
END;

CALL SP_PRODUCTOS(50);

/*
 Crear un cursor que devuelva la cédula, los nombres y apellidos de los 5 estudiantes con mayor promedio de notas.
 */

SELECT AVG(NOTA)
FROM DETALLE;

DECLARE
    CURSOR C_ESTUDIANTES IS
        SELECT CEDULA, NOMBRES, APELLIDOS
        FROM ESTUDIANTES;
    V_CEDULA    ESTUDIANTES.CEDULA%TYPE;
    V_NOMBRES   ESTUDIANTES.NOMBRES%TYPE;
    V_APELLIDOS ESTUDIANTES.APELLIDOS%TYPE;
    v_PROMEDIO  DETALLE.NOTA%TYPE;
BEGIN

    SELECT AVG(NOTA) over () INTO v_PROMEDIO FROM DETALLE;
    DBMS_OUTPUT.PUT_LINE('Promedio de notas: ' || v_PROMEDIO);
END;

DECLARE
    CURSOR C_ESTUDIANTES IS
        SELECT CEDULA, NOMBRES, APELLIDOS
        FROM (SELECT E.CEDULA,
                     E.NOMBRES,
                     E.APELLIDOS,
                     AVG(NOTA) AS PROMEDIO
              FROM ESTUDIANTES E
                       JOIN DETALLE D ON E.CEDULA = D.CEDULA
              GROUP BY E.CEDULA, E.NOMBRES, E.APELLIDOS, D.ID_MATERIA, D.PERIODO
              ORDER BY PROMEDIO DESC)
        WHERE ROWNUM <= 5;

    v_CEDULA    ESTUDIANTES.CEDULA%TYPE;
    v_NOMBRES   ESTUDIANTES.NOMBRES%TYPE;
    v_APELLIDOS ESTUDIANTES.APELLIDOS%TYPE;
BEGIN
    OPEN C_ESTUDIANTES;
    LOOP
        FETCH C_ESTUDIANTES INTO v_CEDULA, v_NOMBRES, v_APELLIDOS;
        EXIT WHEN C_ESTUDIANTES%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(
                ', Cédula: ' || v_CEDULA || ', Nombres: ' || v_NOMBRES ||
                ', Apellidos: ' || v_APELLIDOS);
    END LOOP;
    CLOSE C_ESTUDIANTES;
END;